services:
  agrimarket-api:
    build:
      context: .
      dockerfile: src/Bootstrapper/AgriMarket.Api/Dockerfile
    restart: unless-stopped
    ports:
      - "${AGRI_API_PORT:-5057}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ConnectionStrings__DefaultConnection=Host=${AGRI_POSTGRES_HOST:-agrimarket-db};Port=${AGRI_POSTGRES_DB_PORT:-5432};Database=${AGRI_POSTGRES_DB:-agrimarket_modular};Username=${AGRI_POSTGRES_USER:-postgres};Password=${AGRI_POSTGRES_PASSWORD:-postgres}
      - Jwt__Key=${AGRI_JWT_KEY:-dev-insecure-change-me-please}
      - Jwt__Issuer=${AGRI_JWT_ISSUER:-AgriMarket}
      - Jwt__Audience=${AGRI_JWT_AUDIENCE:-AgriMarket}
      - Cors__Origins__0=${AGRI_CORS_ORIGIN:-http://localhost:8080}
      - Cors__Origins__1=${AGRI_CORS_ORIGIN:-http://localhost:3067}
      - Cors__Origins__1=${AGRI_CORS_ORIGIN:-https://htiits-agrimarket-front.proxy.itcollege.ee}
    networks:
      - agrimarket-net

  agrimarket-web:
    build:
      context: .
      dockerfile: AgriMarket.Web/Dockerfile
    restart: unless-stopped
    ports:
      - "${AGRI_WEB_PORT:-5056}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ConnectionStrings__DefaultConnection=Host=${AGRI_POSTGRES_HOST:-agrimarket-db};Port=${AGRI_POSTGRES_DB_PORT:-5432};Database=${AGRI_POSTGRES_DB:-agrimarket_modular};Username=${AGRI_POSTGRES_USER:-postgres};Password=${AGRI_POSTGRES_PASSWORD:-postgres}
    networks:
      - agrimarket-net

networks:
  agrimarket-net:
    external: true
