<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="6.12.2" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Shared\AgriMarket.Shared\AgriMarket.Shared.csproj" />
    <ProjectReference Include="..\src\Modules\Users\AgriMarket.Modules.Users\AgriMarket.Modules.Users.csproj" />
    <ProjectReference Include="..\src\Modules\Users\AgriMarket.Modules.Users.Contracts\AgriMarket.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="..\src\Modules\Marketplace\AgriMarket.Modules.Marketplace\AgriMarket.Modules.Marketplace.csproj" />
    <ProjectReference Include="..\src\Modules\Marketplace\AgriMarket.Modules.Marketplace.Contracts\AgriMarket.Modules.Marketplace.Contracts.csproj" />
    <ProjectReference Include="..\src\Modules\Bookings\AgriMarket.Modules.Bookings\AgriMarket.Modules.Bookings.csproj" />
    <ProjectReference Include="..\src\Modules\Bookings\AgriMarket.Modules.Bookings.Contracts\AgriMarket.Modules.Bookings.Contracts.csproj" />
    <ProjectReference Include="..\src\Modules\Messaging\AgriMarket.Modules.Messaging\AgriMarket.Modules.Messaging.csproj" />
    <ProjectReference Include="..\src\Modules\Messaging\AgriMarket.Modules.Messaging.Contracts\AgriMarket.Modules.Messaging.Contracts.csproj" />
    <ProjectReference Include="..\AgriMarket.Web\AgriMarket.Web.csproj" />
    <ProjectReference Include="..\src\Bootstrapper\AgriMarket.Api\AgriMarket.Api.csproj" />
  </ItemGroup>

</Project>
